name: Publish

on:
  push:
    branches:
      - 'publish-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  - run: cat index.js
  - run: npx pkg-pr-new publish